baseURL = "https://roee-sec.com/"
languageCode = "en-us"
title = "Roee"
theme = "PaperMod"

enableRobotsTXT = true

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true

[menu]
  [[menu.main]]
    name = "Writeups"
    url = "/writeups/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Labs"
    url = "/labs/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
